### ISSUE TITLE
Email Verification Workflow

### ISSUE THREAD

**Issue by robertjd** [stormpath/stormpath-widget#6]
Need to provide an API, something like:

```
stormpath.verifyEmail([sptoken])
```

If no sptoken is provided, we will try to grab it from the url query parameter.

Because we cannot distinguish between a forgot password flow and an email verification flow (they both generically provide an `sptoken` as a query parameter), the developer will have to manually invoke this API when email verification is required.

DX notes: because directories have email verification disabled by default, I don't expect this to interfere with onboarding.  But the documentation of this widget should show how to manually call this API

## Todos:

- [ ] Update design to match UX in invision
- [ ] Update interface to be `showEmailVerification({ container?: <DomNode>, sptoken?: <String>)`
- [ ] Allow the user to send a new link to their email address, if the link was invalid
